apiVersion: "apps/v1"
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory

  template:
    metadata:
      #annotations:
        #"prometheus.io/scrape": "true"
        #"prometheus.io/port": "9001"
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: "gcr.io/gsa-sandbox-249915/shopping-cart/inventory:latest"
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx256m -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: inventory-application-secret
                  key: secret
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.shopping-cart-kafka-cluster-kafka-brokers.shopping-cart-kafka.svc"
              #value: "_tcp-clients._tcp.strimzi-kafka-brokers.strimzi.svc"
              #value: "_tcp-clients._tcp.strimzi-kafka-brokers.strimzi.svc"
              #value: "_tcp-clients._tcp.cloudflow-kafka-brokers.cloudflow.svc"
              #value: "_clients._tcp.strimzi-kafka-brokers"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512Mi
          ports:
            - name: remoting
              containerPort: 2552
              protocol: TCP
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 9000
              protocol: TCP
            #- name: prometheus
            #  containerPort: 9001
            #  protocol: TCP
            #- name: datadog
            #  containerPort: 8888
            #  protocol: TCP
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: inventory
  annotations:
    external-dns.alpha.kubernetes.io/hostname: inventory.services.lightbend.solutions.
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: inventory
  type: LoadBalancer